#!/usr/bin/env bash

# List all the scripts in /usr/local/bin starting with "bm_"
selected=$(ls ~/nixos/home/scripts/bemenu-scripts/bm-* \
	| awk -F '/' '{print $NF}' \
	| cut -c 4- \
	| bemenu-scripts -p "Select a Script")

# Execute the selected script
~/nixos/home/scripts/bemenu-scripts/bm-$selected
 
